spring.datasource.url=jdbc:mysql://localhost:3306/harry?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=harshal14
spring.jpa.show-sql=true